version: "3"
rpc:
  listen: "tcp://127.0.0.1:6001"
http:
  address: "0.0.0.0:8000"
  middleware:
    - gzip
    - static
  static:
    dir: public
    forbid:
      - .php
      - .htaccess
  pool:
    num_workers: 4
    supervisor:
      max_worker_memory: 100
server:
  command: "php app.php"
  relay: pipes
  user: "app"
  group: "app"
